### PR TITLE
feat/HHH-297: Documentation for Pre Git Commit linting

### PR DESCRIPTION
**Pull request by waletoye**
Screenshot 2022-11-08 at 20 34 21

### CODE REVIEW

**Review by CodeNameNinja — COMMENTED** [review]
Why do we need to add a package.json & .editorconfig.js & .husky should this not come through git.

This would also eliminate the need to run `npm install --save <libary>`

Please send commands, or links to the documentation you used on how we can install dotnet cli.

**Comment by waletoye** [comment]
> Why do we need to add a package.json & .editorconfig.js & .husky should this not come through git.
> 
> This would also eliminate the need to run `npm install --save <libary>`
> 
> Please send commands, or links to the documentation you used on how we can install dotnet cli.

@CodeNameNinja 
You only need to do this if you are setting up for the very first time - which is what I've done already.
For you, you only need to do "npm install" on a branch will has the pre-git commit configured.

Now if you believe we can set it up without those files, then we can explore that.
But I don't know how to do that.

**Comment by CodeNameNinja** [comment]
> > Why do we need to add a package.json & .editorconfig.js & .husky should this not come through git.
> 
> > 
> 
> > This would also eliminate the need to run `npm install --save <libary>`
> 
> > 
> 
> > Please send commands, or links to the documentation you used on how we can install dotnet cli.
> 
> 
> 
> @CodeNameNinja 
> 
> You only need to do this if you are setting up for the very first time - which is what I've done already.
> 
> For you, you only need to do "npm install" on a branch will has the pre-git commit configured.
> 
> 
> 
> Now if you believe we can set it up without those files, then we can explore that.
> 
> But I don't know how to do that.
> 
> 

Okay, I understand, I don't know if you need to document how to set this up as a first time user, or at least we should specify that this is the steps to take if you are starting from scratch,

But the docs should read as if I am a user trying to use this functionality, what do I need to do, to understand and get this to work

**Comment by yskorge** [comment]
> > > Why do we need to add a package.json & .editorconfig.js & .husky should this not come through git.
> > 
> > 
> > > 
> > 
> > 
> > > This would also eliminate the need to run `npm install --save <libary>`
> > 
> > 
> > > 
> > 
> > 
> > > Please send commands, or links to the documentation you used on how we can install dotnet cli.
> > 
> > 
> > @CodeNameNinja
> > You only need to do this if you are setting up for the very first time - which is what I've done already.
> > For you, you only need to do "npm install" on a branch will has the pre-git commit configured.
> > Now if you believe we can set it up without those files, then we can explore that.
> > But I don't know how to do that.
> 
> Okay, I understand, I don't know if you need to document how to set this up as a first time user, or at least we should specify that this is the steps to take if you are starting from scratch,
> 
> But the docs should read as if I am a user trying to use this functionality, what do I need to do, to understand and get this to work

I agree that we only note briefly how it works and how to set it up for new developers :-) you can always add a link to the medium article for reference.

**Comment by waletoye** [comment]
> > > Why do we need to add a package.json & .editorconfig.js & .husky should this not come through git.
> > 
> > > 
> > 
> > > This would also eliminate the need to run `npm install --save <libary>`
> > 
> > > 
> > 
> > > Please send commands, or links to the documentation you used on how we can install dotnet cli.
> > 
> > 
> > 
> > @CodeNameNinja 
> > 
> > You only need to do this if you are setting up for the very first time - which is what I've done already.
> > 
> > For you, you only need to do "npm install" on a branch will has the pre-git commit configured.
> > 
> > 
> > 
> > Now if you believe we can set it up without those files, then we can explore that.
> > 
> > But I don't know how to do that.
> > 
> > 
> 
> Okay, I understand, I don't know if you need to document how to set this up as a first time user, or at least we should specify that this is the steps to take if you are starting from scratch,
> 
> But the docs should read as if I am a user trying to use this functionality, what do I need to do, to understand and get this to work


@CodeNameNinja @yskorge 
I hear two of you

**Review by CodeNameNinja — APPROVED** [review]

**Pull request merged**
